name: hkta-chat
on:
    push:
        branches:
            - 'tecky/feat/whatsapp_web'
    pull_request:
        branches: ['tecky/feat/whatsapp_web']
    workflow_dispatch:

env:
    REPOSITORY_URL: ${{secrets.AWS_REPOSITORY_URL}}
    REGION: ${{ secrets.AWS_REGION }}
    IMAGE_TAG: latest
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
    # Backend Jobs
    server-build:
        runs-on: ubuntu-latest
        container: docker:latest
        services:
            docker:
                image: docker:dind
        steps:
            - uses: actions/checkout@v4
            - run: |
                  apk update
                  apk add --no-cache aws-cli
                  docker login -u AWS -p $(aws ecr get-login-password --region $REGION) $REPOSITORY_URL
                  docker build -t $REPOSITORY_URL/chatwoot:$IMAGE_TAG -f ./docker/Dockerfile .
                  docker push $REPOSITORY_URL/chatwoot:$IMAGE_TAG
